import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

const STYLES = join(import.meta.dirname, '..', 'src', 'styles')
const TARGET = join(STYLES, 'css.generated.ts')

/**
 * Squeezes the stylesheet without rewriting it.
 *
 * Comments go, and every run of whitespace becomes one space. That is the whole
 * transform: in CSS, whitespace is a separator and never a quantity, and the
 * package has no quoted values with internal spaces for it to damage. A
 * cleverer minifier would have to understand `linear(0, 0.002 0.6%, …)`, and
 * shipping a broken spring to save a few hundred bytes is a bad trade.
 */
export function squeezeCss(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s+/g, ' ')
    .replace(/\s*([{};,])\s*/g, '$1')
    .replace(/;}/g, '}')
    .trim()
}

/** Tokens first, then the stylesheet with its `@import` of them removed. */
export async function buildNotiCss(dir: string = STYLES): Promise<string> {
  const [tokens, base] = await Promise.all([
    readFile(join(dir, 'tokens.css'), 'utf8'),
    readFile(join(dir, 'noti.css'), 'utf8'),
  ])

  return squeezeCss(`${tokens}\n${base.replace(/@import\s+['"]\.\/tokens\.css['"]\s*;/, '')}`)
}

function toModule(css: string): string {
  return `/**
 * Generated by \`scripts/generate-css.ts\` from \`tokens.css\` and \`noti.css\`.
 * Do not edit: run \`bun run build\`, or \`bun scripts/generate-css.ts\`.
 *
 * The stylesheet ships inside the JavaScript so that importing the package is
 * enough. \`css.test.ts\` fails if this file and the two \`.css\` sources drift.
 */
export const NOTI_CSS =
  ${JSON.stringify(css)}
`
}

// Only writes when run directly; the test imports the transform instead.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const css = await buildNotiCss()
  await writeFile(TARGET, toModule(css), 'utf8')
  console.log(`generated css.generated.ts (${css.length} chars)`)
}
